### ISSUE TITLE
can you add convert dxf file？

### ISSUE THREAD

**Issue by zhuewizz** [gotranspile/gotrace#1]
I am developing an img to dxf program, I need to convert dxf files, can you add it?

**Comment by dennwc** [comment]
Done! Let me know if it works for you :)

**Comment by zhuewizz** [comment]
thanks very mach ,i will try at once

**Comment by zhuewizz** [comment]
i try it ,very nice tks again ,I want chenge DefaultConfig-->param_default's AlphaMax value,can you tell me how to do?
![image](https://github.com/gotranspile/gotrace/assets/5990209/f7e89c7c-d6f2-4f28-ba5d-f293f5806954)

**Comment by dennwc** [comment]
Sure! You just make a default config and change the desired value:

```go
cfg := gotrace.DefaultConfig()
cfg.AlphaMax = 0.5
paths, err := gotrace.Trace(bm, cfg)
```

**Comment by zhuewizz** [comment]
tks ,tks
